version: '3.8'

networks:
  inception:
services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    volumes:
      - "wp:/var/www/html"
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    expose:
      - "3306"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - "wp:/var/www/html"
    expose:
      - "9000"
    env_file:
      - .env
    restart: always
    networks:
      - inception
volumes:
  wp:
    name: volume_wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jinho/inception/wp
  db:
    name: volume_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jinho/inception/db


