version: '3.8'

networks:
  inception:
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - "volume_db:/var/lib/mysql"
    expose:
      - "3306"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - "volume_wp:/var/www/html"
    expose:
      - "9000"
    env_file:
      - .env
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    volumes:
      - "volume_wp:/var/www/html"
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress
volumes:
  volume_wp:
    name: volume_wp
    driver_opts:
      type: none
      o: bind
      device: /Users/jinho/data/wp/
  volume_db:
    name: volume_db
    driver_opts:
      type: none
      o: bind
      device: /Users/jinho/data/db/


